camera:
    camera:
      ros__parameters:
        accel_fps: -1.0
        accel_frame_id: camera_accel_frame
        accel_info_qos: DEFAULT
        accel_optical_frame_id: camera_accel_optical_frame
        accel_qos: HID_DEFAULT
        align_depth: true
        aligned_depth_to_color_frame_id: camera_aligned_depth_to_color_frame
        allow_no_texture_points: false
        angular_velocity_cov: 0.01
        base_frame_id: camera_link
        clip_distance: 4.0
        color_extrinsics_qos: EXTRINSICS_DEFAULT
        color_fps: 30.0
        color_frame_id: camera_color_frame
        color_height: 480
        color_info_qos: DEFAULT
        color_optical_frame_id: camera_color_optical_frame
        color_qos: SYSTEM_DEFAULT
        color_width: 640
        confidence_fps: -1.0
        confidence_frame_id: camera_confidence_frame
        confidence_height: -1
        confidence_info_qos: DEFAULT
        confidence_optical_frame_id: camera_confidence_optical_frame
        confidence_qos: SYSTEM_DEFAULT
        confidence_width: -1
        decimation.filter_magnitude: 2
        decimation.frames_queue_size: 16
        decimation.stream_filter: 1
        decimation.stream_format_filter: 1
        decimation.stream_index_filter: -1
        depth_fps: -1.0
        depth_frame_id: camera_depth_frame
        depth_height: -1
        depth_info_qos: DEFAULT
        depth_optical_frame_id: camera_depth_optical_frame
        depth_qos: SYSTEM_DEFAULT
        depth_width: -1
        device_type: d455
        enable_accel: true
        enable_color: true
        enable_confidence: true
        enable_depth: true
        enable_fisheye: true
        enable_fisheye1: true
        enable_fisheye2: true
        enable_gyro: true
        enable_infra: true
        enable_infra1: true
        enable_infra2: true
        enable_pointcloud: true
        enable_pose: true
        enable_sync: true
        filters: decimation,spatial,temporal,disparity
        fisheye1_frame_id: camera_fisheye1_frame
        fisheye1_optical_frame_id: camera_fisheye1_optical_frame
        fisheye2_frame_id: camera_fisheye2_frame
        fisheye2_optical_frame_id: camera_fisheye2_optical_frame
        fisheye_extrinsics_qos: EXTRINSICS_DEFAULT
        fisheye_fps: -1.0
        fisheye_frame_id: camera_fisheye_frame
        fisheye_height: -1
        fisheye_info_qos: DEFAULT
        fisheye_optical_frame_id: camera_fisheye_optical_frame
        fisheye_qos: SYSTEM_DEFAULT
        fisheye_width: -1
        gyro_fps: -1.0
        gyro_frame_id: camera_gyro_frame
        gyro_info_qos: DEFAULT
        gyro_optical_frame_id: camera_gyro_optical_frame
        gyro_qos: HID_DEFAULT
        hold_back_imu_for_frames: false
        infra1_extrinsics_qos: EXTRINSICS_DEFAULT
        infra1_frame_id: camera_infra1_frame
        infra1_optical_frame_id: camera_infra1_optical_frame
        infra2_extrinsics_qos: EXTRINSICS_DEFAULT
        infra2_frame_id: camera_infra2_frame
        infra2_optical_frame_id: camera_infra2_optical_frame
        infra_fps: -1.0
        infra_frame_id: camera_infra_frame
        infra_height: -1
        infra_info_qos: DEFAULT
        infra_optical_frame_id: camera_infra_optical_frame
        infra_qos: SYSTEM_DEFAULT
        infra_rgb: true
        infra_width: -1
        initial_reset: false
        json_file_path: ''
        linear_accel_cov: 0.01
        motion_module.enable_motion_correction: true
        motion_module.frames_queue_size: 16
        motion_module.global_time_enabled: true
        odom_frame_id: odom_frame
        ordered_pc: false
        pointcloud.filter_magnitude: 2
        pointcloud.frames_queue_size: 16
        pointcloud.stream_filter: 2
        pointcloud.stream_format_filter: 0
        # pointcloud.stream_index_filter: null
        pointcloud_qos: DEFAULT
        pointcloud_texture_index: 0
        pointcloud_texture_stream: RS2_STREAM_COLOR
        pose_fps: 0.0
        pose_frame_id: camera_pose_frame
        pose_info_qos: DEFAULT
        pose_optical_frame_id: camera_pose_optical_frame
        pose_qos: HID_DEFAULT
        publish_odom_tf: true
        publish_tf: true
        rgb_camera.auto_exposure_priority: false
        rgb_camera.auto_exposure_roi.bottom: 479
        rgb_camera.auto_exposure_roi.left: 0
        rgb_camera.auto_exposure_roi.right: 639
        rgb_camera.auto_exposure_roi.top: 0
        rgb_camera.backlight_compensation: false
        rgb_camera.brightness: 0
        rgb_camera.contrast: 50
        rgb_camera.enable_auto_exposure: true
        rgb_camera.enable_auto_white_balance: true
        rgb_camera.exposure: 166
        rgb_camera.frames_queue_size: 16
        rgb_camera.gain: 64
        rgb_camera.gamma: 300
        rgb_camera.global_time_enabled: true
        rgb_camera.hue: 0
        rgb_camera.power_line_frequency: 3
        rgb_camera.saturation: 64
        rgb_camera.sharpness: 50
        rgb_camera.white_balance: 4600.0
        rosbag_filename: ''
        serial_no: ''
        spatial.filter_magnitude: 2
        spatial.filter_smooth_alpha: 0.5
        spatial.filter_smooth_delta: 20
        spatial.frames_queue_size: 16
        spatial.holes_fill: 1
        spatial.stream_filter: 1
        spatial.stream_format_filter: 1
        spatial.stream_index_filter: -1
        # stereo_module.auto_exposure_limit: null
        stereo_module.auto_exposure_roi.bottom: 479
        stereo_module.auto_exposure_roi.left: 0
        stereo_module.auto_exposure_roi.right: 847
        stereo_module.auto_exposure_roi.top: 0
        # stereo_module.auto_gain_limit: null
        stereo_module.emitter_always_on: false
        stereo_module.emitter_enabled: 1
        stereo_module.emitter_on_off: false
        stereo_module.enable_auto_exposure: true
        stereo_module.error_polling_enabled: true
        stereo_module.exposure: 33000
        stereo_module.frames_queue_size: 16
        stereo_module.gain: 16
        stereo_module.global_time_enabled: true
        stereo_module.hdr_enabled: false
        stereo_module.inter_cam_sync_mode: 0
        stereo_module.laser_power: 150.0
        stereo_module.output_trigger_enabled: false
        stereo_module.sequence_id: 0
        stereo_module.sequence_name: 0
        stereo_module.sequence_size: 2
        stereo_module.thermal_compensation: true
        stereo_module.visual_preset: 0
        temporal.filter_smooth_alpha: 0.4000000059604645
        temporal.filter_smooth_delta: 20
        temporal.frames_queue_size: 16
        temporal.holes_fill: 2
        temporal.stream_filter: 1
        temporal.stream_format_filter: 1
        temporal.stream_index_filter: -1
        tf_publish_rate: 0.0
        unite_imu_method: ''
        usb_port_id: ''
        use_sim_time: false
