version: "3"

services:
    simulation:
        build:
            context: .
            dockerfile: ./Dockerfile
            args:
                - PROJECT_NAME=${COMPOSE_PROJECT_NAME}

        environment:
          - DISPLAY=unix$DISPLAY          
          - QT_X11_NO_MITSHM=1
          - ROS_DOMAIN_ID=0
          - $XAUTHORITY:${XAUTHORITY}

        entrypoint:
            - ./scripts/entrypoint.sh
        volumes:
            - /dev/bus/usb:/dev/bus/usb
            - /tmp/.X11-unix:/tmp/.X11-unix:ro
            - ./..:/home/user/ros2_ws/src
            - /home/${USER}/data:/home/user/data
            - ~/.Xauthority:/root/.Xauthority

        device_cgroup_rules:
          - 'c 189:* rmw'

        network_mode: host
        privileged: true
        stdin_open: true
        tty: true

        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]
                          driver: nvidia
                          options:
                            virtualization: "true"

        entrypoint: ["zsh"]
